name = "repo-hunt"
main = "index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "dc56444c4c955a1653106ccf997c1067"

[[kv_namespaces]]
binding = "REPO_HUNT"
id = "ef57c5ecaa21468bb93597c1656a321b"
